data_root:
  # KITTI sequences root
  data_root_folder: "/home/mjy/datasets/overlapnet_datasets/OverlapNet/kitti/dataset_full/"
  # KITTI sequence 02 velodyne
  valid_scan_folder: "/home/mjy/datasets/kitti/00/velodyne"
  # KITTI sequence 02 computed overlaps
  gt_valid_folder: "/home/mjy/dev/OverlapNet++/kittiHandler/computed_overlap/"
#  calib_file_folder: "/home/mjy/datasets/kitti/data_odometry_calib/dataset/sequences/"
#  pose_file_folder: "/home/mjy/datasets/kitti/data_odometry_poses/dataset/poses/"

training_config:
  # KITTI sequences for training
  training_seqs: ["03", "04", "05","06", "07", "08", "09"]

test_config:
  # KITTI sequence 00 for evaluation
  test_seqs: ["00"]
  # Pretrained model
  test_weights: "/home/mjy/dev/OverlapTransformer/weights/pretrained_overlap_transformer.pth.tar"
  # ground truth
  gt_file: "/home/mjy/dev/OverlapNet++/kittiHandler/overlapnet_test00_methods/loop_gt_seq00_0.3overlap_inactive.npz"